### ISSUE TITLE
Understanding Cache Invalidation Mechanism

### ISSUE THREAD

**Issue by KarthikHolikatti** [falcondev-oss/github-actions-cache-server#132]
### Question: Cache Invalidation Mechanism

Hi team,

I am trying to understand how the cache invalidation works under the hood in `github-actions-cache-server`. Could you provide an explanation or point me to the relevant documentation or code?

Specifically, I am interested in:
- The conditions under which a cache is invalidated.
- How cache keys are managed.
- Any relevant algorithms or implementation details.

Thank you!

**Comment by LouisHaftmann** [comment]
Checkout the [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)

**Comment by KarthikHolikatti** [comment]
@LouisHaftmann My issue is i am using GHA server hosted locally, and during docker build step buildx returns following error:

RESPONSE 400: 400 Invalid block id: KGuevnbfS3RjnjJBUL78/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
ERROR CODE UNAVAILABLE

Below is my setup.

```- name: Docker build
      id: docker_build
      uses: docker/build-push-action@v6.16.0
      with:
        secret-files: ${{ inputs.secret-files }}
        secrets: ${{ inputs.secrets }}
        push: ${{ inputs.publish_to_ecr == 'true' }}
        tags: ${{ steps.full_tag.outputs.name }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        cache-from: type=gha
        cache-to: type=gha,mode=${{ inputs.cache_mode }}
        load: ${{ inputs.load_docker_build == 'true' && inputs.publish_to_ecr != 'true' }}
        build-args: |
          ${{ inputs.docker_build_args }}
        annotations: ${{ steps.metadata.outputs.annotations }}
        platforms: ${{ inputs.platforms }} ```

**Comment by KarthikHolikatti** [comment]
Please help resolve this issue or point out to the issue in my set up!

**Comment by KarthikHolikatti** [comment]
Sorry closed this by mistake!

**Comment by KarthikHolikatti** [comment]
Now i tried the below set up and got following error: WARNING: local cache import at /tmp/.buildx-cache not found due to err: could not lock /tmp/.buildx-cache/index.json.lock: open /tmp/.buildx-cache/index.json.lock: no such file or directory

```
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: buildx-cache-${{ github.event.repository.name }}
        restore-keys: |
          buildx-cache-${{ github.event.repository.name }}

    - name: Docker build
      id: docker_build
      uses: docker/build-push-action@v6.16.0
      with:
        secret-files: ${{ inputs.secret-files }}
        secrets: ${{ inputs.secrets }}
        push: ${{ inputs.publish_to_ecr == 'true' }}
        tags: ${{ steps.full_tag.outputs.name }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=${{ inputs.cache_mode }}
        load: ${{ inputs.load_docker_build == 'true' && inputs.publish_to_ecr != 'true' }}
        build-args: |
          ${{ inputs.docker_build_args }}
        annotations: ${{ steps.metadata.outputs.annotations }}
        platforms: ${{ inputs.platforms }}
```
