### ISSUE TITLE
A question about docker buildx cache upload in the latest release

### ISSUE THREAD

**Issue by enkhjile** [falcondev-oss/github-actions-cache-server#134]
@LouisHaftmann  
Thanks for your amazing service. This cache server is really helping me a lot.  

There was a change in the latest release: `docker buildx cache upload`. Does this mean it now supports Docker Buildx caches? I tried using `docker/build-push-action` as shown below, but it failed.

```yaml
- name: Build and push
  uses: docker/build-push-action@v6
  with:
    context: .
    push: true
    tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPO }}:${{ steps.vars.outputs.version }}
    cache-from: type=gha
    cache-to: type=gha,mode=max
    provenance: false
    platforms: linux/amd64
```
The error pointed to a breaking change in GitHub Actions:
```
#8 importing cache manifest from gha:11113334206725156320
#8 ERROR: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
```
I've been using a workaround to cache Docker layers (https://github.com/docker/build-push-action/issues/252) and was excited about these changes, but I couldn't quite get it to work. Your help would be much appreciated. Thanks again!
