### ISSUE TITLE
Fails with docker action

### ISSUE THREAD

**Issue by joh-klein** [falcondev-oss/github-actions-cache-server#41]
I deployed the cache server right along my runners with kubernetes. The npm jobs worked perfectly. Both uploading and downloading.  But when it came to the `docker/build-push-action@v5` step, cache download and upload failed.

Here is the relevant step:

```
- name: Build and push
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: |
      tag1
      tag2
    cache-from: type=gha
    cache-to: type=gha,mode=max
    file: apps/${{ matrix.app }}/docker/Dockerfile
    provenance: false
    sbom: false
```

The error (downloading the cache):
```
#4 importing cache manifest from gha:6098406064130472668
#4 ERROR: Get "http://cache-server:3000/---token---/_apis/artifactcache/cache?keys=index-buildkit-1-f921bd05&version=693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2": dial tcp: lookup cache-server on 46.38.225.xxx:53: no such host
```

The other error (uploading the cache):
```
ERROR: failed to solve: Get "http://cache-server:3000/---token---/_apis/artifactcache/cache?keys=buildkit-blob-1-sha256%3A067b0579ac4a7184ba4d6bd836719a8fa7286f4d20291d4f10a0b8c85ffca4c9&version=693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2": dial tcp: lookup cache-server on 46.38.225.xxx:53: no such host
```

No idea, where the ip address `46.38.225.xxx` comes from. Its not one of mine (but it is from the hoster I am using).

I have three physical server in my cluster (with 16 runner pods). But in the other step they were perfectly able to connect to the cache server and use it.
