### ISSUE TITLE
Upload fails from docker action

### ISSUE THREAD

**Issue by joh-klein** [falcondev-oss/github-actions-cache-server#42]
Worfklow setup (after I got it to work in #41):

```
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
  with:
    driver: kubernetes

- name: Build and push
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: |
      tag1
      tag2
    cache-from: type=gha
    cache-to: type=gha,mode=max
    file: app/docker/Dockerfile
    provenance: false
    sbom: false
```
At the start of the step, I can see this in the logs from the cache server:
```
[cache-server] ⚙ No exact primary matches found
[cache-server] ⚙ No restore keys provided
[cache-server] ⚙ Get: No cache entry found for [ 'index-buildkit-1-f921bd05' ] 693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2
[cache-server] ⚙ Get: Getting cache entry for [ 'buildkit-blob-1-sha256:0d0c16747d2c6b6c26c064652afcb964c15f1b1e596ec052b2aa19b83948ae27' ] 693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2
[cache-server] ⚙ Finding key match { key:
   'buildkit-blob-1-sha256:0d0c16747d2c6b6c26c064652afcb964c15f1b1e596ec052b2aa19b83948ae27',
  version: '693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2',
  restoreKeys: undefined }
```

At the end of the docker build step, the cache upload fails with:
```
#16 exporting to GitHub Actions Cache
#16 preparing build cache for export
#16 preparing build cache for export 0.1s done
#16 writing layer sha256:0d0c16747d2c6b6c26c064652afcb964c15f1b1e596ec052b2aa19b83948ae27 done
#16 ERROR: error writing layer blob: Error
------
 > exporting to GitHub Actions Cache:
------
ERROR: failed to solve: error writing layer blob: Error
```

I don't know (yet) how to get more meaningful output
