### ISSUE TITLE
zstd: /*stdin*\: unsupported format 

### ISSUE THREAD

**Issue by labis-suro** [falcondev-oss/github-actions-cache-server#54]
I use macOS and use version github actions cache v4 and use last version docker image and i got this.
```
zstd: /*stdin*\: unsupported format 
tar: Error opening archive: Child process exited with status 1
Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 1
```

**Comment by LouisHaftmann** [comment]
Are those logs from the actions runner or from the cache server?

**Comment by labis-suro** [comment]
Hmm no logs, but cache saved

**Comment by labis-suro** [comment]
How check logs another, i check with docker logs

**Comment by labis-suro** [comment]
![image](https://github.com/user-attachments/assets/795a7147-d813-429b-b909-1a0b953fb5a5)
![image](https://github.com/user-attachments/assets/a9fa464e-60f4-4907-a0c4-fb4204bdcae4)
logs from actions

**Comment by LouisHaftmann** [comment]
Are you running the actions runner bare bones or dockerized?

**Comment by labis-suro** [comment]
@LouisHaftmann bare

**Comment by LouisHaftmann** [comment]
Do you have tar installed on your system? Try using the tar command in terminal

**Comment by labis-suro** [comment]
Yes, installed

**Comment by LouisHaftmann** [comment]
Could you share the following:

- docker compose file of the cache server
- version of the cache server
- GitHub workflow file

Also try enabling debug logs of the cache server by setting `DEBUG=true` env var

**Comment by labis-suro** [comment]
docker compose file 
```
version: '3.9'

services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    ports:
      - '3000:3000'
    environment:
      URL_ACCESS_TOKEN: example
      DEBUG: true
      API_BASE_URL: http://192.168.0.2:3000
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data:
  ```
  Version cache server latest
  
  Workflow file
  ```
  name: CI Expo

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build-iphone:
    needs: build-android
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - uses: oven-sh/setup-bun@v2
        with:
         bun-download-url: "https://github.com/oven-sh/bun/releases/download/bun-v1.1.24/bun-darwin-x64.zip"
      - name: Install deps
        run: bun install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.3'
           bundler-cache: true

      - name: ☕️ Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.15.2

      - uses: actions/cache@v4
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-  
      - name: Generate ios directory
        run: npx expo prebuild -p ios
       
```
docker compose file 
```
version: '3.9'

services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    ports:
      - '3000:3000'
    environment:
      URL_ACCESS_TOKEN: example
      DEBUG: true
      API_BASE_URL: http://192.168.0.2:3000
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data:
  ```
  Version cache server latest
  
  Workflow file
  ```
  name: CI Expo

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build-iphone:
    needs: build-android
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - uses: oven-sh/setup-bun@v2
        with:
         bun-download-url: "https://github.com/oven-sh/bun/releases/download/bun-v1.1.24/bun-darwin-x64.zip"
      - name: Install deps
        run: bun install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.3'
           bundler-cache: true

      - name: ☕️ Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.15.2

      - uses: actions/cache@v4
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-  
      - name: Generate ios directory
        run: npx expo prebuild -p ios
       
```docker compose file 
```
version: '3.9'

services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    ports:
      - '3000:3000'
    environment:
      URL_ACCESS_TOKEN: example
      DEBUG: true
      API_BASE_URL: http://192.168.0.2:3000
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data:
  ```
  Version cache server latest
  
  Workflow file
  ```
  name: CI Expo

on:
  workflow_dispatch:

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  build-iphone:
    needs: build-android
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - uses: oven-sh/setup-bun@v2
        with:
         bun-download-url: "https://github.com/oven-sh/bun/releases/download/bun-v1.1.24/bun-darwin-x64.zip"
      - name: Install deps
        run: bun install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.3'
           bundler-cache: true

      - name: ☕️ Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.15.2

      - uses: actions/cache@v4
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-  
      - name: Generate ios directory
        run: npx expo prebuild -p ios
       
```
cache-server-1  | [cache-server] ℹ Using database driver: sqlite
cache-server-1  | [cache-server] ℹ Migrating database...
cache-server-1  | [cache-server] ⚙ Migration results []
cache-server-1  | [cache-server] ✔ Database migrated
cache-server-1  | [cache-server] ℹ Using storage driver: filesystem
cache-server-1  | [cache-server] ℹ Cleaning up cache entries older than 90d with schedule 0 0 * * * (next run: 8/21/2024, 12:00:00 AM)
cache-server-1  | Listening on http://[::]:3000
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: POST /<secret_token>/_apis/artifactcache/caches
cache-server-1  | [cache-server] ⚙ Reserve: Reserving cache for macOS-pods- b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 59208892
cache-server-1  | [cache-server] ⚙ Reserve: Cache reserved for macOS-pods- b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 59208892 with upload 9836212093
cache-server-1  | [cache-server] ⚙ Response: POST /<secret_token>/_apis/artifactcache/caches > 200
cache-server-1  | [cache-server] ⚙ Request: PATCH /<secret_token>/_apis/artifactcache/caches/9836212093
cache-server-1  | [cache-server] ⚙ Request: PATCH /<secret_token>/_apis/artifactcache/caches/9836212093
cache-server-1  | [cache-server] ⚙ Upload: Uploading chunk for upload 9836212093
cache-server-1  | [cache-server] ⚙ Upload: Uploading chunk for upload 9836212093
cache-server-1  | [cache-server] ⚙ Upload: Chunks uploaded for id 9836212093
cache-server-1  | [cache-server] ⚙ Response: PATCH /<secret_token>/_apis/artifactcache/caches/9836212093 > 204
cache-server-1  | [cache-server] ⚙ Upload: Chunks uploaded for id 9836212093
cache-server-1  | [cache-server] ⚙ Response: PATCH /<secret_token>/_apis/artifactcache/caches/9836212093 > 204
cache-server-1  | [cache-server] ⚙ Request: POST /<secret_token>/_apis/artifactcache/caches/9836212093
cache-server-1  | [cache-server] ⚙ Commit: Committing cache for upload 9836212093
cache-server-1  | [cache-server] ⚙ Commit: Committing cache for id 9836212093
cache-server-1  | [cache-server] ⚙ Commit: Cache committed for id 9836212093
cache-server-1  | [cache-server] ⚙ Response: POST /<secret_token>/_apis/artifactcache/caches/9836212093 > 204
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
cache-server-1  | [cache-server] ⚙ Request: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Get: Getting cache entry for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92
cache-server-1  | [cache-server] ⚙ Finding key match { key: 'macOS-pods-',
cache-server-1  |   version: 'b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92',
cache-server-1  |   restoreKeys: [ 'macOS-pods-' ] }
cache-server-1  | [cache-server] ⚙ Get: Cache entry found for [ 'macOS-pods-', 'macOS-pods-' ] b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 with id macOS-pods-
cache-server-1  | [cache-server] ⚙ Response: GET /<secret_token>/_apis/artifactcache/cache?keys=macOS-pods-%2CmacOS-pods-&version=b68d6c0afabb7ff28ac9b2bc95c042799da7f5ecc1a0f8e6e3c9c655fe220b92 > 200
```

**Comment by labis-suro** [comment]
@DrJume Yes, installed
![Uploading Screenshot 2024-08-21 at 11.02.25.png…]()

**Comment by LouisHaftmann** [comment]
I tried reproducing the error but it worked for me. 

Could you try running this workflow and check if the cache works:

```yaml
name: "test"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/cache@v4
        with:
          path: test.txt
          key: test-key-1
      - name: create test file
        run: echo "test" > test.txt
  test2:
    needs: test
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/cache@v4
        with:
          path: test.txt
          key: test-key-1

```

If it doesn't work please try re-running with debug logs enabled and share the logs.
