### ISSUE TITLE
Runners are not able to pickup the self hosted cache-server

### ISSUE THREAD

**Issue by asutosh23** [falcondev-oss/github-actions-cache-server#66]
Hey Louis,

I am trying to setup the cache-server, but the runners are not able to connect to the self hosted cache server.

Cache Server Manifest
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gha-cache-server
  namespace: gha-cache-server
spec:
  serviceName: gha-cache-server
  replicas: 1
  selector:
    matchLabels:
      app: gha-cache-server
  template:
    metadata:
      labels:
        app: gha-cache-server
    spec:
      containers:
      - name: gha-cache-server
        image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: gcs-credentials
          mountPath: /app/.gcs
          readOnly: true
        - name: cache-data
          mountPath: /app/.data
        env:
        - name: URL_ACCESS_TOKEN
          value: "w5AQ9VKtzc"
        - name: API_BASE_URL
          value: "http://<Load Balancer IP of this app>:3000"
        - name: TEMP_DIR
          value: "/app/.data/tmp"
        - name: STORAGE_DRIVER
          value: "gcs"
        - name: STORAGE_GCS_BUCKET
          value: "gha-cache-server-storage"
        - name: STORAGE_GCS_SERVICE_ACCOUNT_KEY
          value: "/app/.gcs/sa-gcs-cache-server-keyfile.json"
        - name: DEBUG
          value: "true"
      volumes:
        - name: gcs-credentials
          secret:
            secretName: gha-cache-server-secret
            items:
            - key: sa-gcs-cache-server-keyfile.json
              path: sa-gcs-cache-server-keyfile.json
        - name: cache-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gha-cache-server-lb
  namespace: gha-cache-server
  labels:
    app: gha-cache-server
  annotations:
    load-balancer.hetzner.cloud/location: hil
spec:
  selector:
    app: gha-cache-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
```

Runner Image

```
FROM ghcr.io/actions/actions-runner:2.319.1

# modify actions runner binaries to allow custom cache server implementation
RUN sed -i 's/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x43\x00\x41\x00\x43\x00\x48\x00\x45\x00\x5F\x00\x55\x00\x52\x00\x4C\x00/\x41\x00\x43\x00\x54\x00\x49\x00\x4F\x00\x4E\x00\x53\x00\x5F\x00\x43\x00\x41\x00\x43\x00\x48\x00\x45\x00\x5F\x00\x4F\x00\x52\x00\x4C\x00/g' /home/runner/bin/Runner.Worker.dll

# Switch to root user to install packages
USER root 

# Update package lists and install required tools
RUN apt-get update && apt-get install -y \
  unzip \
  wget \
  g++ \
  make \
  zip \
  python3 \
  python3-pip \
  iproute2 \
  net-tools \
  pkg-config \
  curl \

# Install GitHub CLI 
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
  apt update && \
  apt install -y gh

ENV ACTIONS_CACHE_URL="http://<Load Balancer IP of the cache server>:3000/w5AQ9VKtzc/"

# Switch back to the runner user  
USER runner
```

I have deployed the image using ARC runners in a cluster
The cache server is deployed in another cluster

Error logs from the cache server
```
╰─▶▶ k logs gha-cache-server-0                                                                                                                                                                   ⎈  | luxorlabs ⇆ gha-cache-server 
[cache-server] ℹ Cleaning up cache entries older than 90d with schedule 0 0 * * * (next run: 10/9/2024, 12:00:00 AM)
[cache-server] ℹ 🚀 Starting GitHub Actions Cache Server (v3.1.0)
[cache-server] ℹ Using database driver: sqlite
[cache-server] ℹ Migrating database...
[cache-server] ✔ Database migrated
[cache-server] ℹ Using storage driver: gcs
Listening on http://[::]:3000

[cache-server]  ERROR  Response: GET /w5AQ9VKtzc/ > 404
 Cannot find any route matching /w5AQ9VKtzc/.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /healthz > 404
 Cannot find any route matching /healthz.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /w5AQ9VKtzc/caches > 404
 Cannot find any route matching /w5AQ9VKtzc/caches.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /w5AQ9VKtzc/ > 404
 Cannot find any route matching /w5AQ9VKtzc/.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /w5AQ9VKtzc > 404
 Cannot find any route matching /w5AQ9VKtzc.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /w5AQ9VKtzc/caches > 404
 Cannot find any route matching /w5AQ9VKtzc/caches.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)

[h3] Please prefer using `message` for longer error messages instead of `statusMessage`. In the future, `statusMessage` will be sanitized by default.

[cache-server]  ERROR  Response: GET /<secret_token>/_apis/artifactcache/cache > 400
 Invalid query parameters: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "keys"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "version"
    ],
    "message": "Required"
  }
]

  {
  "code": "invalid_type",
  "expected": "string",
  "received": "undefined",
  "path": [
  "keys"
  ],
  "message": "Required"
  },
  {
  "code": "invalid_type",
  "expected": "string",
  "received": "undefined",
  "path": [
  "version"
  ],
  "message": "Required"
  }
  ]
  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at handler (server/chunks/routes/_token/_apis/artifactcache/cache.get.mjs:35:13)
  at _callHandler (server/chunks/runtime.mjs:2712:22)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.handler (server/chunks/runtime.mjs:2832:19)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)


[cache-server]  ERROR  Response: GET /favicon.ico > 404
 Cannot find any route matching /favicon.ico.

  at createError$1 (server/chunks/runtime.mjs:1886:15)
  at matchHandler (server/chunks/runtime.mjs:3017:16)
  at Object.handler (server/chunks/runtime.mjs:3056:19)
  at Object.handler (server/chunks/runtime.mjs:2832:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3102:7)
  ```

Could you please help to figure out what's wrong here, my runners are still picking up the default cache servers of GitHub
