### ISSUE TITLE
Failed to save: commitCache failed: Cache service responded with 500

### ISSUE THREAD

**Issue by dmzrio** [falcondev-oss/github-actions-cache-server#80]
i try upgrade from v.3.10 to v4.0.0, but when in my workflow i found error `Failed to save: commitCache failed: Cache service responded with 500`. i think this is happened because selinux and i try disable security context on my manifest but i still get it error. How to fix it?

```
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
```

<img width="867" alt="Screenshot 2024-11-25 at 04 51 47" src="https://github.com/user-attachments/assets/9974bea7-e9a4-405c-a4a5-ddd18746df4f">

<img width="1551" alt="Screenshot 2024-11-25 at 05 02 07" src="https://github.com/user-attachments/assets/a9528aa4-19d2-4786-bc1b-b63d8c1b6531">
