### ISSUE TITLE
ERROR  Failed to initialize storage driver: UnknownError

### ISSUE THREAD

**Issue by colachg** [falcondev-oss/github-actions-cache-server#86]
For those who want to use S3 driver but encountered this kind of error:
```
[+] Running 1/0
 ✔ Container github-action-cache-server  Created                                                                                                                       0.0s 
Attaching to github-action-cache-server
github-action-cache-server  | [cache-server] ℹ Cleaning up cache entries older than 90d with schedule 0 0 * * * (next run: 1/9/2025, 12:00:00 AM)
github-action-cache-server  | [cache-server] ℹ 🚀 Starting GitHub Actions Cache Server (v4.0.1)
github-action-cache-server  | [cache-server] ℹ Using database driver: sqlite
github-action-cache-server  | (node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
github-action-cache-server  | (Use `node --trace-deprecation ...` to show where the warning was created)
github-action-cache-server  | [cache-server] ℹ Migrating database...
github-action-cache-server  | [cache-server] ✔ Database migrated
github-action-cache-server  | [cache-server] ℹ Using storage driver: s3
github-action-cache-server  | 
github-action-cache-server  |  ERROR  Failed to initialize storage driver: UnknownError
github-action-cache-server  | 
github-action-cache-server  |   at throwDefaultError (server/node_modules/@smithy/smithy-client/dist-cjs/index.js:846:20)
github-action-cache-server  |   at server/node_modules/@smithy/smithy-client/dist-cjs/index.js:855:5
github-action-cache-server  |   at de_CommandError (server/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4739:14)
github-action-cache-server  |   at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
github-action-cache-server  |   at async server/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
github-action-cache-server  |   at async server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:485:18
github-action-cache-server  |   at async server/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
github-action-cache-server  |   at async server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
github-action-cache-server  |   at async server/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14
github-action-cache-server  |   at async server/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
```

You need to set  both of the `STORAGE_S3_ENDPOINT` and `STORAGE_S3_REGION` together.  You can get the regular s3 endpoint [here](https://docs.aws.amazon.com/general/latest/gr/s3.html)

On my side, the configuration looks like this:
```
services:
  cache-server:
    container_name: github-action-cache-server
    image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
    ports:
      - '80:3000'
    environment:
      URL_ACCESS_TOKEN: random_token
      API_BASE_URL: http://localhost
      STORAGE_DRIVER: s3
      STORAGE_S3_BUCKET: gha-cache-bucket
      STORAGE_S3_ENDPOINT: s3.ap-northeast-1.amazonaws.com
      STORAGE_S3_REGION: ap-northeast-1
      STORAGE_S3_ACCESS_KEY: access_key
      STORAGE_S3_SECRET_KEY: secret_key
      STORAGE_S3_PORT: 443
      STORAGE_S3_USE_SSL: true
    volumes:
      - cache-data:/app/.data

volumes:
  cache-data:
```
